---
- name: Install Jenkins
  hosts: localhost
  become: yes
  tasks:
    - name:  YUM Update
      yum:
        name: '*'
        state: latest

    - name: Add the Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import a key file from Jenkins-CI to enable installation from the package
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: YUM Update
      yum:
        name: '*'
        state: latest

    - name: Install Java (Amazon Linux 2)
      shell: amazon-linux-extras install java-openjdk11 -y

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Enable and Start Jenkins
      ansible.builtin.systemd:
        enabled: yes
        name: jenkins
        state: started
